version: '3'
services:
  payara:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    build: 
     context: .
     dockerfile: dockerfilePostgres
    restart: always
    volumes:
      - vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: db1234
      POSTGRES_USER: user
      POSTGRES_DB: mantenimientodb
volumes:
  vol:
